
/* These syntax are used in postgresql  pgadmin4 sql editor*/

/*Creating customer table*/
create table customer(
ID int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
email varchar(255) NOT NULL,
username varchar(255) NOT NULL,
password varchar(1024) NOT NULL	
);

/*Creating bank detail table table*/
create table bank_detail(
ID int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
account_number int NOT NULL UNIQUE,
card_number int NOT NULL UNIQUE
);



 /* Here first customer id  column is added and use foreign  key to connect*/
ALTER TABLE bank_detail ADD customer_Id int;                        

ALTER TABLE bank_detail
ADD FOREIGN KEY (customer_id) REFERENCES customer(ID);


/*Creating Account table*/
 /* Here first create enum types and then create table with enums data field*/                                                                     
CREATE TYPE account_type AS ENUM ('income','expenses','assets',' liabilities','cash','bank','capital');

create table accounts(
ID int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(50) Not NULL,
balance int DEFAULT 0,
types account_type 
);

ALTER TABLE accounts  ADD customer_Id int; 

ALTER TABLE bank_detail
ADD FOREIGN KEY (customer_id) REFERENCES customer(ID);


/*Creating Transactions  table*/

create table transactions(
ID int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
date date Not NULL,
amount decimal(24,2)
);

ALTER TABLE transactions  ADD customer_id int; 
ALTER TABLE transactions  ADD debit int; 
ALTER TABLE transactions  ADD credit int; 

ALTER TABLE transactions
ADD FOREIGN KEY (customer_id) REFERENCES customer(ID);

ALTER TABLE transactions
ADD FOREIGN KEY (debit) REFERENCES accounts(ID);

ALTER TABLE transactions
ADD FOREIGN KEY (credit) REFERENCES accounts(ID);


/*Creating Personal Details  table*/
create table personal_details(
ID int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
first_Name varchar(255),
middle_Name varchar(255),
last_name varchar(255),
gender varchar(255),
contact_number int,	
home_street_address varchar(255),
home_zip_code int,
home_state varchar(255),
home_country varchar(255)
);

ALTER TABLE personal_details  ADD customer_id int; 

ALTER TABLE personal_details
ADD FOREIGN KEY (customer_id) REFERENCES customer(ID);


/*refactoring code*/

CREATE TYPE gender AS ENUM ('male','female','others');
ALTER TABLE personal_details  drop gender;
ALTER TABLE personal_details  ADD gender gender;

ALTER TABLE accounts  drop balance;
ALTER TABLE accounts ADD balance decimal(24,2);